production:
  url: url
  bucket: bucket_name
  access_key: access_key
  secret_access_key: secret_access_key
  region: region

development:
  url: url
  bucket: bucket_name
  access_key: access_key
  secret_access_key: secret_access_key
  region: region