production:
  driver: <%= ENV.fetch("STORAGE_DRIVER") { 'local' } %>
  local_storage_path: <%= ENV.fetch("LOCAL_STORAGE_DRIVER_PATH") { 'storage/files' } %>

development:
  driver: <%= ENV.fetch("STORAGE_DRIVER") { 'local' } %>
  local_storage_path: <%= ENV.fetch("LOCAL_STORAGE_DRIVER_PATH") { 'storage/files' } %>
